<?php

namespace App\Filament\Resources\PeriodicSpendResource\Pages;

use App\Filament\Resources\ActivityResource;
use App\Filament\Resources\PeriodicSpendResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditPeriodicSpend extends EditRecord
{
    protected static string $resource = PeriodicSpendResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        return ActivityResource::splitStartEndDate($data); // TODO: Change the autogenerated stub
    }

    public function mutateFormDataBeforeFill(array $data): array
    {
        return ActivityResource::combineStartEndDate($data);
    }
}
