<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\InertiaDashboardController
 */
class InertiaDashboardControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function get_blog_edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $blogPost = \App\Models\BlogPost::factory()->create();
        $blogPosts = \App\Models\BlogPost::factory()->times(3)->create();

        $response = $this->get('blog/edit/{blog_post_id}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_blog_listing_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $blogPosts = \App\Models\BlogPost::factory()->times(3)->create();

        $response = $this->get(route('posts'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_blog_new_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('blog/new');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_dashboard_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('dashboard'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function post_blog_edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $blogPost = \App\Models\BlogPost::factory()->create();

        $response = $this->post('blog/edit/{blog_post_id}', [
            // TODO: send request data
        ]);

        $response->assertRedirect('/blog/listing');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function post_blog_new_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('blog/new', [
            // TODO: send request data
        ]);

        $response->assertRedirect('/blog/listing');

        // TODO: perform additional assertions
    }

    // test cases...
}
