<?php

namespace App\Filament\Resources\ActivityResource\Pages;

use App\Filament\Resources\ActivityResource;
use Filament\Actions\DeleteAction;
use Filament\Resources\Pages\EditRecord;

class EditActivity extends EditRecord
{
    protected static string $resource = ActivityResource::class;

    protected function getActions(): array
    {
        return [
            DeleteAction::make(),
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        return ActivityResource::splitStartEndDate($data); // TODO: Change the autogenerated stub
    }

    public function mutateFormDataBeforeFill(array $data): array
    {
        return ActivityResource::combineStartEndDate($data);
    }
}
