<?php

namespace Tests\Feature\Http\Controllers\Auth;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Auth\VerifyEmailController
 */
class VerifyEmailControllerTest extends TestCase
{
    /**
     * @test
     */
    public function invoke_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('verification.verify', ['id' => $id, 'hash' => $hash]));

        $response->assertRedirect(intended(RouteServiceProvider::HOME.'?verified=1'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function __invoke_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \App\Http\Controllers\Auth\VerifyEmailController::class,
            '__invoke',
            \Illuminate\Foundation\Auth\EmailVerificationRequest::class
        );
    }

    // test cases...
}
